on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'

name: dockerhub

jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          sudo apt-get install -y qemu-user qemu qemu-user-static
          docker buildx build --platform linux/amd64 -t timglabisch/protoc:${{ steps.vars.outputs.tag }}_amd64 --push .
          docker buildx build --platform linux/arm64 -t timglabisch/protoc:${{ steps.vars.outputs.tag }}_arm64 --push .
          docker manifest create timglabisch/protoc:${{ steps.vars.outputs.tag }} timglabisch/protoc:${{ steps.vars.outputs.tag }}_amd64 timglabisch/protoc:${{ steps.vars.outputs.tag }}_arm64
          docker manifest push timglabisch/protoc:${{ steps.vars.outputs.tag }}